apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: api-key
spec:
  backendType: secretsManager
  # # optional: specify role to assume when retrieving the data
  # roleArn: arn:aws:iam::123456789012:role/test-role
  # When running locally i'm injecting my AWS creds (Access/Secret keys) as K8 secrets
  data:
    - key: prod/k8-external-secrets/api-key
      name: api_key
